### ISSUE TITLE
Bug for Android Build

### ISSUE THREAD

**Issue by horochovec** [Differential/meteor-vulcanize#21]
Well,

I have this issue using Meteor + Meteor-Vulcanize to build a app for Android using OSX (https://github.com/meteor/meteor/issues/5089)

I'm trying to create a Polymer Project, my build for web works fine, but for Mobile, I have many problems.

I try to build the localmarket example and build for Android works fine, so, I think I have a problem when I using the Vulcanize plugin:

horochovec: mediaglobe$ VULCANIZE=true meteor build --directory ../mobile-build --server http://xyz.meteor.com --verbose --debug 
% Running build for platforms: [ 'android' ]  
% Building the cordova build project          
% Bundling the web.cordova program of the app 
=> Vulcanize: Importing vulcanized file...   \
% Ensuring the cordova build project          
% Reading the mobile control file             
% Running the mobile control file             
% Copying resources for mobile apps           
% Writing new config.xml                      
% Ensuring that platforms in cordova build project are in sync
% Running synchronously:  /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms: android 3.6.4
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ios

% Ensuring plugins in the cordova build project are in sync { 'org.apache.cordova.console': '0.2.13',
  'org.apache.cordova.file': '1.3.3',
  'org.apache.cordova.file-transfer': '0.5.0',
  'org.apache.cordova.device': '0.2.13',
  'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'org.apache.cordova.statusbar': '0.1.10',
  'org.apache.cordova.splashscreen': '1.0.0' }
% Getting installed plugins for project       
% Running synchronously:  /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: com.meteor.cordova-update 0.0.1 "CordovaUpdate"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins lock: { 'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2' }
% Copying the JS/CSS files one level up       
% Removing the www folder                     
% Writing www/application folder              
% Writing index.html                          
% Writing meteor_cordova_loader               
% Writing a default index.html for cordova app
% Running the build command                   
% Running synchronously:  /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ '--verbose', 'build', 'android' ]
% Done building the cordova build project     
=> Vulcanize: Importing vulcanized file...   \
                                              
/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EACCES, rename '/Users/mediaglobe/Projects/meteor-examples/mobile-build/bundle'
    at Object.Future.wait (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as rename] (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
    at Object.files.renameDirAlmostAtomically (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:810:11)
    at [object Object]._.extend.complete (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/builder.js:482:11)
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1933:13
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2147:20
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2040:31)
    at buildCommand (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:894:30)
    at Command.main.registerCommand._.extend.name [as func] (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:746:12)
    at /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
    - - - - -
horochovec: mediaglobe$

**Comment by dragGH102** [comment]
@horochovec Just in case you didn't yet figure it out :)
EACCES is usually solved by using sudo

By the way, are you using Polymer from polymer-project or a library/module for Meteor?

**Comment by horochovec** [comment]
@dragGH102 I gave up using the Meteor on this project, many problems and a lot of incompatibility with Polymer. Other problems were also detected in the build in Cordova, anyway ...

**Comment by dragGH102** [comment]
no problem @horochovec. as an hint, this is an interesting solution: https://github.com/atoy40/meteor-polymer-music
it basically install Polymer and use it (it's an example using meteor-elements package) and at first sight works pretty well
