### ISSUE TITLE
Error on deploy application

### ISSUE THREAD

**Issue by horochovec** [Differential/meteor-vulcanize#23]
meteor --version
Meteor 1.2-rc.12 (Need this version because 1.1.x don't work to build mobile applications)

horochovec:project mediaglobe$ VULCANIZE=true meteor deploy http://xyz.meteor.com --debug
Deploying to xyz.meteor.com.           
=> Vulcanize: Importing vulcanized file...   /
                                              
/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.7-rc.12.o5yy0f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Must provide either sourcePath or data
    at new File (/tools/isobuild/bundler.js:244:13)
    at /tools/isobuild/bundler.js:727:19
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:723:17
    at Array.forEach (native)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:701:19)
    at /tools/isobuild/bundler.js:492:12
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:483:18)
    at /tools/isobuild/bundler.js:2062:14
    at /tools/isobuild/bundler.js:2144:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.7-rc.12.o5yy0f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2143:7
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2047:31)
    at Object.bundleAndDeploy (/tools/meteor-services/deploy.js:402:32)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands.js:1293:29)
    at /tools/cli/main.js:1377:23

**Comment by jstoup111** [comment]
I'm getting this issue as well.

**Comment by ThaumRystra** [comment]
+1
